### ISSUE TITLE
Wrongful errors for formData / type: integer

### ISSUE THREAD

**Issue by netzkind** [CacheControl/hippie-swagger#21]
Affected version: HippieSwagger 2.1.0

Specification:
```
parameters:
  quantity:
    name: quantity
    in: formData
    type: integer
    format: int32
    required: true
```

Code/Request:
```
hippieSwagger(app, dereferencedSwagger)
	.form()
	.post('/url')
	.send({
		quantity: 1
	})
	.expectStatus(200)
```

Result:
>  Error: Invalid format for parameter {quantity}, received: 1.  errors:data should be integer

As far as i have seen, this happens because hippie-swagger decomposes the query-string for validating the parameters - meaning 1 (integer) has changed to "1" (string), thus failing in ajv.
